### ISSUE TITLE
Phat vita perma death?

### ISSUE THREAD

**Issue by animekai** [SKGleba/IMCUnlock#1]
My vita after following everything,  now just doesn't turn on,  when prompted to restart or install enso,  i restarted my visa and now it doesn't turn on, worth 98% of battery is not possible to be off of juice,  tried to hold 20 seconds the power button but nothing,  i think it killed my vita 😥

**Comment by SKGleba** [comment]
1) What Firmware?
2) What exact vita model?
3) Was enso installed before flash?
4) Did you do a clean boot? (without plugins in config)
5) Did you start IMCUnlock immediately after clean boot? (or after hencore)

**Comment by animekai** [comment]
1.- 3.65
2.- fat 1000
3.-enso 3.65 by the flow way before the h-encore release
4.- i reboot the vita with L to desactivate plugins, so no.
5.- after the restart, yes.

Then made the install, rebooted and never awake again

**Comment by SKGleba** [comment]
"If you are using ENSO NSKBL hack, make sure that the correct enso installer is installed."
...
"If you are a user of ENSO NSKBL hack - launch the enso installer and install enso"
...
Yeah, the vita is perma bricked.

**Comment by animekai** [comment]
Something i can do? Like getting the battery  out and hard reset?  Something?

**Comment by animekai** [comment]
I know is my fault but,  i think your readme was not fully noob proof, i think maybe there are gonna be a lot users perma bricking their vitas.

**Comment by megapro17** [comment]
Watch less anime, blockhead.
