### ISSUE TITLE
Need help.

### ISSUE THREAD

**Issue by SMNFXCN** [SKGleba/IMCUnlock#10]
I have a few questions.
1. Can I use the latest version of ensō_ex or will I brick? (it's already installed.) https://github.com/SKGleba/enso_ex/releases/tag/v3.0
2. How much space do I need on ux0 to backup vd0/pd0/tm0/id_data?
3. Will it effect my memory card?
4. >1GB - Default on 2XXX and TV units, a ~1GB imc partition, ur0 1.5GB, on Phats requires formatting the new partition via settings or safemode.

Will formatting the new partition effect my memory card?
5. If I brick will I be able to restore my .img backups?

**Comment by SKGleba** [comment]
1) yea you can
2) 500mb should be enough
3) no
4) no
6) if you brick you wont be able to do anything cuz.. brick
