### ISSUE TITLE
this emmc type is not supported

### ISSUE THREAD

**Issue by fennectech** [SKGleba/IMCUnlock#11]
I am using it on a 2000 to attempt to disable imc0 entirely as i dont use it however i get "This EMMC type is not supported" and it say sto contact you here.

**Comment by SKGleba** [comment]
Open imcunlock, press triangle, dump mbr, send me ux0:data/mbr.img

**Comment by fennectech** [comment]
Triangle does nothing  do you happen to mean "backup id data" ?

**Comment by fennectech** [comment]
Here it is.  https://cdn.discordapp.com/attachments/572222503146225704/575532920375083018/mbr.img

**Comment by SKGleba** [comment]
oh yeah, i will add support for it in the next ver

**Comment by fennectech** [comment]
Thanks :).  2.5gb ur0 here i come

**Comment by fennectech** [comment]
When you get that added can you let me try it out with a beta ?
