### ISSUE TITLE
Chose the 1GB solution , but the ur0 partition size still 2.5GB in vitashell view

### ISSUE THREAD

**Issue by whmzsu** [SKGleba/IMCUnlock#14]
I select the following solution. 
1GB - Default on 2XXX and TV units, a ~1GB imc partition, ur0 1.5GB, on Phats requires formatting the new partition via settings or safemode.

All worked well , but in the vitashell, the ur0 partition still show 2.5GB size.

**Comment by SKGleba** [comment]
Normal, related to PBR.
