### ISSUE TITLE
Feature request: "Maximize ur0" profile.

### ISSUE THREAD

**Issue by ghost** [SKGleba/IMCUnlock#15]
After installing Enso, an imc partition is no longer necessary as you can either use an official MC, a sd2Vita or install to ur0.
Since ur0 is the only internal partition that the user can still directly access, you should add a profile to maximize it.
Basically:
* No imc partition
* Minimize pd0 and ud0 (and other rarely-written system partitions if possible)
* Maximize ur0

Since only sizes are changed and all partitions are still there, there should be minimal problems (apart from updates but it is not needed because of the ref00d hack).

**Comment by SKGleba** [comment]
Ill add a pc tool to configure the partition sizes soonTM
