### ISSUE TITLE
Undo Hybrid ur0-pd0

### ISSUE THREAD

**Issue by Xerczsese** [SKGleba/IMCUnlock#19]
When I select a different configuration it does change but still leaves the hybrid drive. Is there a way to remove this to go back to stock configuration? I did this through vita deploy so I downloaded this standalone version and hybrid configuration does not revert back to stock either. I have tried multiple ways to revert back but nothing has worked and I do not want to brick my vita. Not really a big deal just experimenting. Just not adding up after I did the hybrid drive and tried to revert back. TIA
![storage sizes](https://user-images.githubusercontent.com/88244313/233792479-6acd9d61-f090-4be9-90df-34cfeaebb2a1.jpg)

**Comment by SKGleba** [comment]
Remember that to "apply" the configuration of ur0,ud0,pd0,etc you need to reformat the storages, eg via safemode's restore option.
This can be skipped with the 100MB ux0 option as the changes to ur0 are negligible.
Not formatting might cause various crashes and errors, besides visually appearing wrong in vitashell.
