### ISSUE TITLE
something want to know about enso installers

### ISSUE THREAD

**Issue by jerrytom88888** [SKGleba/IMCUnlock#2]
I wonner know whether we can use the enso installers you provided for h-encore or not？ i download the enso installer for 365(vs0 nl), install and execute for my vita(365 hencore), but after rebooting, no enso here.  so the enso intallers must use with IMCUnlock？ and what the NHKBL mean, i am confused.
thank u！！

**Comment by SKGleba** [comment]
Its for people already on enso (before installing imcunlock), in this case - update365.
NSKBL - Non Secure Kernel Boot Loader

**Comment by Sir-Charles** [comment]
Sorry about commenting on a closed issue, but my questions are relevant to the topic..


1. Does the normal/default enso installer use ur0 or vs0? And is this just for the tai config or something else?

2. Do we have to use your enso installers specifically, or will the normal molecule/flow ones work?

3. Are your versions of the enso installer updated to v1.1?
