### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by 5685C4A059D5** [SKGleba/IMCUnlock#4]
Not sure what the cause is. During installation only the gamesd and henkaku plugins were loaded.
I followed the instructions and chose to create a 300MB ux0, then installed 3.60 enso NL.
After rebooting, welcome park still works and pd0 shows up normally.
I tried the installation again but the result was the same.
Thinking gamesd might have interfered with mounting, I removed that plugin and rebooted. Welcome park still works and no memory card showed up in settings.

**Comment by SKGleba** [comment]
Install this version: https://mega.nz/#!OlBCnayR!N1YcmM6iiU8RP5j3gEdTCOrIHkxLinsxq5yJmtmqf4A .
And follow the steps from the guide, after reboot, go to ux0:data/, there should be a file called "ptable.img", send me it please.

**Comment by 5685C4A059D5** [comment]
Unfortunately to confirm whether the installation worked or not I removed the gamesd plugin. Right now I cannot install packages.

**Comment by SKGleba** [comment]
On 3.60 use MLTHaku, then after installing the plugin - reinstall henkaku holding R.

**Comment by 5685C4A059D5** [comment]
[ptable.zip](https://github.com/SKGleba/IMCUnlock/files/2195644/ptable.zip)
Here it is. I also included the file the enso installer created.

**Comment by SKGleba** [comment]
Hmm, the patch is applied (in the real partition table), tho the bruteforce may not work.
Could you reinstall the fw via safemode (after applying the mod)?

**Comment by 5685C4A059D5** [comment]
After running IMCUnlock and the enso installer, then installing 3.60
through QCMA in safe mode, after rebooting the result is exactly the same
as before (except henkaku is gone ofc)

2018-07-15 21:57 GMT+07:00 SKGleba <notifications@github.com>:

**Comment by SKGleba** [comment]
Hmm, very interesting. 
Try with this version: https://mega.nz/#!GtomDaIZ!FdzcRM2Jnv7OlgxqCK6V9uoqjgjMf3I7MjwXmBe4rnc
It should create three files in ux0:data - 
- "ptable_cln.img" - dumped partition table (before install).
- "ptable_loc.img" - partition table dumped from the local MBR image.
- "ptable_act.img" - dumped partition table (after install).
Please send me them.

**Comment by 5685C4A059D5** [comment]
[ptable_.zip](https://github.com/SKGleba/IMCUnlock/files/2198982/ptable_.zip)
Here are the files

**Comment by SKGleba** [comment]
ok,i had another user with the same problem, try resetting tai config (i.e from hencore)

**Comment by 5685C4A059D5** [comment]
I don't use h-encore though.
I reinstalled MLThaku before running imcunlock, does that count?

2018-07-18 5:37 GMT+07:00 SKGleba <notifications@github.com>:

**Comment by SKGleba** [comment]
MLTHaku messes up perms, so yeah, you should be on a stock henkaku.

**Comment by 5685C4A059D5** [comment]
OK so I just reset tai with the henkaku installer, added the gamesd plugin,
rebooted and ran imcunlock.
Same results.

Vào 5:07 CH, Th 4, 18 thg 7, 2018 SKGleba <notifications@github.com> đã
viết:

**Comment by SKGleba** [comment]
Try v3.
