### ISSUE TITLE
Sony memory not recognised

### ISSUE THREAD

**Issue by ghost** [SKGleba/IMCUnlock#6]
I used a phat Vita 3.68 and accidentally disabled the internal memory after getting it to work. Now, I lost everything, and the Vita won't recognise any kind of memory card. The system doesn't react to it, like it doesn't exist. Whenever I try to format, it fails and shows C1-2755-9. And the system only resets. I tried rebuilding the database but nothing worked.

The internal memory I had was the 2.5 GB one version. The IMCUnlock I used was used 2.5.2.

Update: I tried to format it again through the Settings and it can recognise whether a memory card is inserted. However, nothing more than that since it just claims to have formatted the memory and restarts the system, then asks me to format the memory again and give me the same error.

**Comment by SKGleba** [comment]
Its clearly written in the readme that you should use v3's 0mb option to disable it.
